# This is a basic workflow to help you get started with Actions

name: Generate repo.yml

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
    types:
      - closed

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  if_merged:
    if: github.event.pull_request.merged == true
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v3
        if: ${{ github.event_name == 'pull_request' }}
        with:
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          ref: ${{ github.event.pull_request.head.ref }}
          
      - uses: actions/checkout@v3
        if: ${{ github.event_name != 'pull_request' }}
      
      # Download latest fonz release
      - uses: robinraju/release-downloader@v1.5
        with:
          repository: "1player/fonz"
          latest: true
          fileName: "fonz.linux.x86_64"
          out-file-path: ".bin/fonz"
      
      # Generate repo file
      - name: Run a one-line script
        run: |
          export PATH="$GITHUB_WORKSPACE/.bin:$PATH"
          scripts/generate-repo.sh
          
      # Commit updated repo file
      - uses: EndBug/add-and-commit@v9
        with:
          add: "./repo.yml --force"
          default_author: github_actions
          message: "Regenerate repo.yml"
